config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :welcome, :vehicles

  root to: 'welcome#index'
  
  get '/enter' => 'users#show'

  get '/login' => 'welcome#index'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  get '/newvehicle' => 'vehicles#new'
  post '/vehicle' => 'vehicles#create'
  get '/edit' => 'vehicles#edit'
  patch '/editvehicle' => 'vehicles#update'
  get '/delete' => 'vehicles#destroy'
  
  patch '/oilchange' => 'vehicles#oilchange'
  get '/miles' => 'vehicles#mpg' 
  
  get '/log' => 'auto_logs#new'
  post '/entry' => 'auto_logs#create'
  
  get '/note' => 'notes#new'
  post '/list' => 'notes#create'
  
  get '/deletelog' => 'auto_logs#destroy'
  get '/deletenote' => 'notes#destroy'
  
  get '/sale' => 'vehicles#sell'
  
  get '/sales' => 'vehicles#sales'
  
  get '/inspect' => 'vehicles#inspect'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto_log.rb
class AutoLog < ApplicationRecord
  belongs_to :vehicle
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :vehicle
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :vehicles
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :auto_logs
  has_many :notes
  belongs_to :user
  
  
  def mpg_calc(miles, gallons)
    if miles === "0" || gallons === "0" || miles.empty? || gallons.empty?
       mpg = 1
    else
      mpg = miles.to_i/gallons.to_i
    end
    return mpg
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/auto_logs_controller.rb
class AutoLogsController < ApplicationController
  
  def new
    @vehicle = Vehicle.find(params[:vehicleid])
  end
  
  def create
    unless auto_params[:entry].empty?
      auto = AutoLog.new(auto_params)
      auto.save
      redirect_to vehicle_path(auto_params[:vehicle_id])
    end
  end
  
  def destroy
    log = AutoLog.find(params[:delete])
    vehicle = log.vehicle_id
    log.delete
    redirect_to vehicle_path(vehicle)
  end
  
  
  private
  
  def auto_params
    params.require(:auto_entry).permit(:entry, :vehicle_id)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  def new
    @vehicle = Vehicle.find(params[:vehicleid])
  end
  
  
  def create
    unless note_params[:list].empty?
      note = Note.new(note_params)
      note.save
      redirect_to vehicle_path(note_params[:vehicle_id])
     end
  end
    
  def destroy
    note = Note.find(params[:delete])
    vehicle = note.vehicle_id
    note.delete
    redirect_to vehicle_path(vehicle)
  end
  
  
  private
  
  def note_params
    params.require(:note).permit(:list, :vehicle_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def show
    @vehicles = current_user.vehicles
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  def index
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end
  
  def inspect
    @vehicle = Vehicle.find(params[:price])
  end

  def new
  end

  def create
    unless vehicle_params[:make].empty? || vehicle_params[:model].empty?
      vehicle = Vehicle.new(vehicle_params)
      vehicle.save
      redirect_to user_path(current_user.id)
    end
  end
  
  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:vehicle][:vehicle_id])
    @vehicle.update(vehicle_params)
    @vehicle.save
    redirect_to vehicle_path(@vehicle.id)
  end
  
  def oilchange
    vehicle = Vehicle.find(params[:vehicle][:id])
    vehicle.update(mileage: params[:vehicle][:mileage])
    log = AutoLog.new(entry: ("Oil change @ " + params[:vehicle][:mileage]).to_s, vehicle_id: params[:vehicle][:id])
    log.save
    vehicle.save
    redirect_to vehicle_path(vehicle.id)
  end
  
  def mpg
    @vehicle = Vehicle.find(params[:id])
    @vehicle.update(mpg: @vehicle.mpg_calc(params[:miles], params[:gallons]))
    @vehicle.save
    redirect_to vehicle_path(@vehicle.id)
  end

  
  def destroy
    Vehicle.delete(params[:delete])
    redirect_to user_path(current_user.id)
  end
  
  def sell
    @vehicle = Vehicle.find(params[:id])
    unless params[:price].empty?
      @vehicle.update(sale_price: params[:price])
    end
    if @vehicle.for_sale === false
      @vehicle.update(for_sale: true)
    else
      @vehicle.update(for_sale: false)
    end
    @vehicle.save
    redirect_to vehicle_path(@vehicle.id)
  end
  
  def sales
    @vehicles = Vehicle.all
  end

  private
  

  def vehicle_params
    params.require(:vehicle).permit(:make, :model, :year, :color, :mpg, :sale_price, :mileage, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auto_logs_helper.rb
module AutoLogsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/auto_logs/new.html.erb
<body class='garage'>
	<%= render 'layouts/header' %><br>
	<div class='entry'><br>
		<p class='vehicleentry'>
			<%= @vehicle.make %>
			<%= @vehicle.model %>
		</p>
		<%= form_for :auto_entry, url: '/entry' do |f| %>
		  <%= f.text_field :entry, placeholder: "Add a service entry", :autocomplete => :off %><br>
		
		  <%= f.hidden_field :vehicle_id, :value => params[:vehicleid] %><br>
		  <%= f.submit :title => "Submit", :type => :image, :src => image_path("/images/login.png") %>
		<% end %>
	</div>
</body>

app/views/layouts/_about.html.erb
<div id='aboutpage'><br>
	<h1>About Service Supreme</h1>
	<p>Welcome to the Service Supreme app! Log in or Sign up to get started!<p>
	<p> Add a vehicle to your garage, where you can keep a service log and notes on your vehicle.</p>
</div>

app/views/layouts/_back.html.erb
<div id='back'>
	<%=link_to "Back", vehicle_path(@vehicle.id)%>
</div>

app/views/layouts/_header.html.erb
<div class="navbar">
  <a href=<%=root_path%> title='Home' id='home'><img id='logo' src='/images/servicelogo.jpg'></a>
  <h1 id='title'>Service Supreme</h1>
  <button type="submit" title="About Service Supreme" id='about'><img src="/images/question.png" width="25" height="25"></button>
</div>
<% if current_user %>
	<div class="navbar2">
	  <div class="dropdown">
	    <button class="dropbtn">Menu
	      <i class="fa fa-caret-down"></i>
	    </button>
	    <div class="dropdown-content">
	      <% if current_user %>
	        <a id='logout' href="/logout" onclick="return confirm('Are you sure?')">Log out</a>
		  	<%= link_to image_tag("/images/garageicon.png", id: "garage", title: "Garage "), user_path(current_user.id)%>
		  	<a id='forsale' href="/sales" >For sale</a>
	      <% end %>
	    </div>
	  </div>
	</div>
<% end %>
<%= render 'layouts/about' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Service Supreme</title>
    <link rel="shortcut icon" type="image/png" href="/images/servicelogo2.jpg">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>

    
  </head>
  <%= yield %>
</html>

app/views/notes/new.html.erb
<body class='garage'>
	<%= render 'layouts/header' %><br>
	<div class='entry'><br>
		<p class='vehicleentry'>
			<%= @vehicle.make %>
			<%= @vehicle.model %>
		</p>
		<%= form_for :note, url: '/list' do |f| %>
		  <%= f.text_field :list, placeholder: "Add a service note", :autocomplete => :off %><br>
		
		  <%= f.hidden_field :vehicle_id, :value => params[:vehicleid] %><br>
		  <%= f.submit :title => "Submit", :type => :image, :src => image_path("/images/login.png") %>
		<% end %>
	</div>
</body>

app/views/users/index.html.erb
<body>
  	<%= render 'layouts/header' %>	
	<% if current_user %>
		<a href="/newvehicle">Add a Vehicle<a>
	<% end %>
</body>

app/views/users/new.html.erb
<body class='welcome'>
  	<%= render 'layouts/header' %><br>
  	<div class='formbox'>
		<h2>Sign up / <a href="/login">Log in</a></h2>
		<div class='forms'>
		  <%= form_for :user, url: '/users' do |f| %>
		    <%= f.text_field :name, placeholder: "Username", :autocomplete => :off %><br>
		    <%= f.text_field :email, placeholder: "Email", :autocomplete => :off %><br>
		    <%= f.password_field :password, placeholder: "Password"%><br>
		    <%= f.password_field :password_confirmation, placeholder: "Password Confirmation"%><br><br>
		    <%= f.submit "Signup", :type => :image, :src => image_path("/images/login.png") %><br>
		  <% end %>
		</div>
	</div>
	<div id="door"></div>
</body>

app/views/users/show.html.erb
<body class='garage'>
  	<%= render 'layouts/header' %><br>
  	<div class='chalkboard'>
  		<a href="/newvehicle" title='Add Vehicle' id='addvehicle'><img src="/images/plus.png" width="30" height="30"><a>
		<% if !current_user.vehicles.empty? %><br>
			<% @vehicles.each do |vehicle| %>
				  <%= vehicle.make %>
				  <%= vehicle.model %>
				  <%=link_to image_tag("/images/tool.png", class: "tool", title: "Service " + vehicle.model), vehicle_path(vehicle.id)%>
				  <form action='/delete' id='deletevehicle'>
				      <button type="submit" title="Delete <%= vehicle.model %>" name='delete' value="<%= vehicle.id %> " onclick="return confirm('Are you sure?')"><img src="/images/can1.png" width="25" height="25"></button>
				  </form>
			<%end%>
		<%else%>
			<h3 id='stored'>No vehicles stored</h3>
		<%end%>
	</div>
</body>

app/views/vehicles/edit.html.erb
<body class='garage'>
  	<%= render 'layouts/header' %>
	<br>
	<div class='formbox'><br>
		Edit <%=@vehicle.model%>
		<div class='forms'><br>
			<%= form_for @vehicle, url: '/editvehicle' do |f| %>
			  <%= f.text_field :make, placeholder: "Make", :autocomplete => :off %><br>
			  <%= f.text_field :model, placeholder: "Model", :autocomplete => :off %><br>
			  <%= f.number_field :year, placeholder: "Year", :autocomplete => :off %><br>
			  <%= f.text_field :color, placeholder: "Color", :autocomplete => :off %><br>
			  <%= f.number_field :mileage, placeholder: "Mileage", :autocomplete => :off %><br>
			  <%= f.hidden_field :user_id, :value => current_user.id %><br>
			  <%= f.hidden_field :vehicle_id, :value => @vehicle.id %>
			  <%= f.submit :title => "Submit", :type => :image, :src => image_path("/images/login.png") %>
			<% end %>
		</div>
	</div>
</body>

app/views/vehicles/inspect.html.erb
<body class='garage'>
	 <%= render 'layouts/header' %><br>
	 <div class='vehicleshow'><br>
	 	<p class='vehicletitle'>
		 	<%= @vehicle.year %>
			<%= @vehicle.make %>
			<%= @vehicle.model %>
		</p><br>
		Color:  <%= @vehicle.color %><br>
		Mileage:  <%= @vehicle.mileage %><br>
		MPG:  <%= @vehicle.mpg %><br>
	 </div>
	 
	<div class='log'><br>
		<%if !@vehicle.auto_logs.empty?%>
			<p class='vehicleentry'>
				<%=@vehicle.model%> Service Log<br><br>
			</p>
			<%@vehicle.auto_logs.each do |log|%>
				<%=log.entry%><br>
			<%end%>
		<%else%>
			Service Log Empty<br>
		<%end%>
	</div>
		
	<div class='note'><br>
		<%if !@vehicle.notes.empty?%>
			<p class='vehicleentry'>
				<%=@vehicle.model%> Notes<br><br>
			</p>
			<%@vehicle.notes.each do |note|%>
				<%=note.list%><br>
			<%end%>
		<%else%>
			Notes Empty<br>
		<%end%>
	</div>
</body>

app/views/vehicles/log.html.erb
<body>
  	<%= render 'layouts/header' %>	
	<%@vehicle.auto_logs.each do |log|%>
		<%=log.entry%>
	<%end%>
</body>

app/views/vehicles/mpg.html.erb
 <div class='miles'><br>
	<form action='/miles'>
		<input type ='double' name='miles' placeholder="Miles Traveled" autocomplete="off"></input>
		<input type ='double' name='gallons' placeholder="Gallons Used" autocomplete="off"></input>
	    <button type="submit" title="<%= @vehicle.model %>" name='id' value="<%= @vehicle.id %>">Calculate Vehicle MPG</button>
	</form>
 </div>

app/views/vehicles/new.html.erb
<body>
  	<%= render 'layouts/header' %>	
	<br>
	<%= form_for :vehicle, url: '/vehicle' do |f| %>
	  <%= f.text_field :make, placeholder: "Make", :autocomplete => :off %><br>
	  <%= f.text_field :model, placeholder: "Model", :autocomplete => :off %><br>
	  <%= f.number_field :year, placeholder: "Year", :autocomplete => :off %><br>
	  <%= f.text_field :color, placeholder: "Color", :autocomplete => :off %><br>
	  <%= f.number_field :mileage, placeholder: "Mileage", :autocomplete => :off %><br>
	  <%= f.hidden_field :user_id, :value => current_user.id %>
	  <%= f.submit "Submit" %>
	<% end %>
</body>

app/views/vehicles/oilchange.html.erb
 <div class='oilchange'><br>
	Next oil change @ <%= @vehicle.mileage.to_i + 3000 %><br>
	  
	<%= form_for @vehicle, url: '/oilchange' do |f| %>
	  <%= f.number_field :mileage, :autocomplete => :off, :placeholder => "New Mileage" %><br>
	  <%= f.hidden_field :id, :value => @vehicle.id %>
	  <%= f.submit "Oil Change" %>
	<% end %>
</div>

app/views/vehicles/sales.html.erb
<body class='garage'>
  	<%= render 'layouts/header' %><br>
  	<div class='salepage'>
		<% unless @vehicles.any?{|vehicle| vehicle.for_sale === true} %>
			<h3 id='stored'>No vehicles for sale</h3>
		<% else %>
			<h3 id='stored'>Vehicles for sale</h3>
			<%@vehicles.each do |vehicle|%>
				<% if vehicle.for_sale === true && vehicle.sale_price > 0%>
					<%= vehicle.make %>
					<%= vehicle.model %>
					$<%= vehicle.sale_price %>
					<form action='/inspect' id='sale'>
					    <button type="submit" title="Inspect" name='price' value="<%=vehicle.id %>"><img class='tool' src="/images/tool.png" width="25" height="25"></button>
					</form>
				<%end%>
			<%end%>
		<%end%>
	</div>
</body>

app/views/vehicles/sell.html.erb
<body class='garage'>
  	<%= render 'layouts/header' %>
	<br>
	<div class='formbox'><br>
		Sell <%=@vehicle.model%>
		<div class='forms'><% end %>
			<%= form_for @vehicle, url: '/sellvehicle' do |f| %>
			  <%= f.number_field :sale_price, placeholder: "Sale Price", :autocomplete => :off %><br>
			  <%= f.hidden_field :user_id, :value => current_user.id %><br>
			  <%= f.hidden_field :vehicle_id, :value => @vehicle.id %>
			  <%= f.submit :title => "Submit", :type => :image, :src => image_path("/images/login.png") %>
			<% end %>
		</div>
	</div>
</body>

app/views/vehicles/show.html.erb
<body class='garage'>
	 <%= render 'layouts/header' %><br>
	 <div class='vehicleshow'><br>
	 	<p class='vehicletitle'>
		 	<%= @vehicle.year %>
			<%= @vehicle.make %>
			<%= @vehicle.model %>
		</p>
		<%=link_to image_tag("/images/tool.png", class: "edit", title: "Edit " + @vehicle.model), edit_vehicle_path(@vehicle.id)%><br>
		Color:  <%= @vehicle.color %><br>
		Mileage:  <%= @vehicle.mileage %><br>
		MPG:  <%= @vehicle.mpg %><br>
		<div id='sell' <% if @vehicle.for_sale === true%>style="background-color:lightgreen"<%else%>style="background-color:red"<%end%>>
			<form action='/sale' id='sale'>
				<input type ='integer' title="Update Sale Price" id ='price' name='price' placeholder="<%=@vehicle.sale_price%>" autocomplete="off"></input>
			    <button type="submit" title="Sell Vehicle" name='id' value="<%= @vehicle.id %>">Sell</button>
			</form>
		</div>
			
		<form action='/miles' id='mpgform'>
			<input type ='double' name='miles' placeholder="Miles Traveled" autocomplete="off"></input>
			<input type ='double' name='gallons' placeholder="Gallons Used" autocomplete="off"></input><br>
		    <button type="submit" title="Calculate <%= @vehicle.model %> MPG" name='id' value="<%= @vehicle.id %>"><img src="/images/calc.png" width="25" height="25"></button>
		</form>
		
		<div class='oilchange'><br>
			<%= form_for @vehicle, url: '/oilchange' do |f| %>
			  <%= f.number_field :mileage, :autocomplete => :off, :placeholder => "Miles Traveled" %><br>
			  <%= f.hidden_field :id, :value => @vehicle.id %>
			  <%= f.submit "Oil Change", :title => "Updates mileage and submits a log entry", :type => :image, :src => image_path("/images/oilcan.png") %>
			<% end %>
		</div>
	 </div>
	 
	<div class='log'><br>
		<%if !@vehicle.auto_logs.empty?%>
			<p class='vehicleentry'>
				<%=@vehicle.model%> Service Log<br><br>
			</p>
			<%@vehicle.auto_logs.each do |log|%>
				<form action='/deletelog'>
					<%=log.entry%>
				    <button type="submit" title='Delete Log Entry' name='delete' value="<%= log.id %>" onclick="return confirm('Are you sure?')"><img src="/images/can1.png" width="15" height="15"></button>
				</form>
			<%end%>
		<%else%>
			Service Log Empty<br>
		<%end%>
		<form action='/log'>
		    <button type="submit" title="Add Service Entry" name='vehicleid' value="<%= @vehicle.id %>"><img src="/images/service.png" width="30" height="30"></button><br>
		</form><br>
	</div>
		
	<div class='note'><br>
		<%if !@vehicle.notes.empty?%>
			<p class='vehicleentry'>
				<%=@vehicle.model%> Notes<br><br>
			</p>
			<%@vehicle.notes.each do |note|%>
				<form action='/deletenote'>
					<%=note.list%>
				    <button type="submit" title='Delete Note' name='delete' value="<%= note.id %>" onclick="return confirm('Are you sure?')"><img src="/images/can1.png" width="15" height="15"></button>
				</form>
			<%end%>
		<%else%>
			Notes Empty<br>
		<%end%>
		<form action='/note'>
		    <button type="submit" title="Add <%= @vehicle.model %> Note" name='vehicleid' value="<%= @vehicle.id %>"><img src="/images/note1.png" width="25" height="25"></button><br>
		</form><br>
	</div>
</body>

app/views/welcome/index.html.erb
<body class='welcome'>
  	<%= render 'layouts/header' %>
		<% if !current_user %><br>
		<div class='formbox'>
			<h2>Log in / <a href="/signup">Sign up</a></h2>
			<div class='forms' id='login'>
			  <%= form_tag '/login' do %>
			    <%= text_field_tag :email, nil, :placeholder => 'Email', :autocomplete => "off"%><br>
			    <%= password_field_tag :password, nil, :placeholder => 'Password', :autocomplete => "off"%><br><br>
			    <%= submit_tag "Login", :type => :image, :src => image_path("/images/login.png") %><br><br>
			  <% end %>
			</div>
		</div>
	<% elsif current_user %>
		<h1 id='enter'><a href="/enter" id='entry'>Enter Garage</a></h1>
		<div id='opener'>
			<button id="open"><img src="/images/up.png" title="Open" width="40" height="40"></button>
			<button id="close"><img src="/images/down.png" title="Close" width="40" height="40"></button>
		</div>
	<% end %>
	<div id="door"></div>
</body>